using AuthApi.Framework.Common.Enums;
using AuthApi.Framework.SharedKernel.Api;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace AuthApi.Framework.SharedKernel.Filters;

/// <summary>
/// Action filter that wraps controller responses into a standardized
/// <see cref="ApiResult"/> format before they are sent to the client.
/// This ensures all API responses follow a consistent structure.
/// </summary>
public class ApiResultFilterAttribute : ActionFilterAttribute
{
    /// <summary>
    /// Executes before the action result is written to the response.
    /// Converts supported ActionResult types into ApiResult objects.
    /// </summary>
    /// <param name="context">The context for the executing result.</param>
    public override void OnResultExecuting(ResultExecutingContext context)
    {
        // Handle responses such as: return Ok(data);
        if (context.Result is OkObjectResult okObjectResult)
        {
            // Wrap the returned object inside a successful ApiResult.
            var apiResult = new ApiResult<object>(
                true,
                ApiResultStatusCode.Success,
                okObjectResult.Value!
            );

            context.Result = new JsonResult(apiResult)
            {
                StatusCode = okObjectResult.StatusCode
            };
        }

        // Handle responses such as: return Ok();
        else if (context.Result is OkResult okResult)
        {
            // Return a success response without any data.
            var apiResult = new ApiResult(
                true,
                ApiResultStatusCode.Success
            );

            context.Result = new JsonResult(apiResult)
            {
                StatusCode = okResult.StatusCode
            };
        }

        // Handle HTTP 400 Bad Request responses.
        else if (context.Result is ObjectResult badRequestObjectResult &&
                 badRequestObjectResult.StatusCode == 400)
        {
            string message = null!;

            switch (badRequestObjectResult.Value)
            {
                // Model validation errors generated by ASP.NET Core.
                case ValidationProblemDetails validationProblemDetails:

                    // Collect all validation error messages.
                    var errorMessages = validationProblemDetails.Errors
                        .SelectMany(p => p.Value)
                        .Distinct();

                    message = string.Join(" | ", errorMessages);
                    break;

                // Legacy SerializableError support.
                case SerializableError errors:

                    var errorMessages2 = errors
                        .SelectMany(p => (string[])p.Value)
                        .Distinct();

                    message = string.Join(" | ", errorMessages2);
                    break;

                // Custom error message returned by the action.
                case var value when value is not null and not ProblemDetails:

                    message = badRequestObjectResult.Value?.ToString()!;
                    break;
            }

            // Wrap the error inside ApiResult.
            var apiResult = new ApiResult(
                false,
                ApiResultStatusCode.BadRequest,
                message!
            );

            context.Result = new JsonResult(apiResult)
            {
                StatusCode = badRequestObjectResult.StatusCode
            };
        }

        // Handle HTTP 404 Not Found responses.
        else if (context.Result is ObjectResult notFoundObjectResult &&
                 notFoundObjectResult.StatusCode == 404)
        {
            string message = null!;

            // Use the custom message if available.
            if (notFoundObjectResult.Value is not null and not ProblemDetails)
                message = notFoundObjectResult.Value?.ToString()!;

            var apiResult = new ApiResult(
                false,
                ApiResultStatusCode.NotFound,
                message
            );

            context.Result = new JsonResult(apiResult)
            {
                StatusCode = notFoundObjectResult.StatusCode
            };
        }

        // Handle responses returned as plain text.
        else if (context.Result is ContentResult contentResult)
        {
            var apiResult = new ApiResult(
                true,
                ApiResultStatusCode.Success,
                contentResult.Content!
            );

            context.Result = new JsonResult(apiResult)
            {
                StatusCode = contentResult.StatusCode
            };
        }

        // Handle object results that have no explicit status code
        // and are not already wrapped in ApiResult.
        else if (context.Result is ObjectResult objectResult &&
                 objectResult.StatusCode == null &&
                 objectResult.Value is not ApiResult)
        {
            var apiResult = new ApiResult<object>(
                true,
                ApiResultStatusCode.Success,
                objectResult.Value!
            );

            context.Result = new JsonResult(apiResult)
            {
                StatusCode = objectResult.StatusCode
            };
        }

        // Continue executing the remaining pipeline.
        base.OnResultExecuting(context);
    }
}